import "./globals.css";
import { Inter } from "next/font/google";
import { ProviderRTK } from "@/redux/providers";
import { NavHomePage } from "@/components/Navigation/HomePage";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavHomePage />
        <ProviderRTK>{children}</ProviderRTK>
      </body>
    </html>
  );
}
